In [1]:
import pandas as pd

# Import SQL Alchemy
from sqlalchemy import create_engine

# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float

In [2]:
df_1 = pd.read_csv("movies_metadata.csv")

In [3]:
df_1.head()

,id,imdb_id,title,release_date,spoken_languages,genres,runtime,production_companies,production_countries,budget,revenue,overview,tagline,vote_average,vote_count,homepage,popularity
0,329440,tt3387542,The Forest,1/7/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",95,"[{'name': 'Lava Bear Films', 'id': 32300}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",10000000,40055439,"Set in the Aokigahara Forest, a real-life plac...",Everyone comes here looking for a way out,4.8,478,http://theforestisreal.com/,7.384688
1,368031,tt3352390,Friend Request,1/7/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",92,"[{'name': 'Wiedemann & Berg Filmproduktion', '...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",9900000,2400000,"Enjoying college life as a popular student, La...",Be careful who you click with.,5.3,376,http://www.w-b-film.de/,14.282584
2,300671,tt4172430,13 Hours: The Secret Soldiers of Benghazi,1/13/2016,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",144,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'MT', 'name': 'Malta'}, {'iso_...",50000000,69411370,An American Ambassador is killed during an att...,"When everything went wrong, six men had the co...",7.0,963,http://www.thirteenhoursmovie.com/,18.022579
3,299687,tt2304933,The 5th Wave,1/14/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",112,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...",38000000,109906372,16-year-old Cassie Sullivan tries to survive i...,Protect Your Own,5.6,1993,https://www.facebook.com/5thWaveMovie/,10.788263
4,276905,tt1594972,Norm of the North,1/14/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",86,"[{'name': 'Lionsgate', 'id': 1632}, {'name': '...","[{'iso_3166_1': 'US', 'name': 'United States o...",18000000,17062499,"The stereoscopic 3D animated family film ""Norm...",Bear to be different,4.1,124,http://www.normofthenorth.movie,7.008103

In [4]:
df_2 = pd.read_csv("movie_scraped_data.csv")
df_2.head()

,imdb_id,actors,boxoffice,director,poster_link,production_company,ratings,writer
0,tt3387542,"Natalie Dormer, Eoin Macken, Stephanie Vogt, O...","$21,818,536",Jason Zada,https://m.media-amazon.com/images/M/MV5BMjAwMz...,Gramercy Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Nick Antosca, Sarah Cornwell, Ben Ketai"
1,tt3352390,"Alycia Debnam-Carey, William Moseley, Connor P...","$3,758,792",Simon Verhoeven,https://m.media-amazon.com/images/M/MV5BNGFhZj...,Entertainment Studios Motion Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Matthew Ballen, Philip Koch, Simon Verhoeven"
2,tt4172430,"John Krasinski, James Badge Dale, Pablo Schrei...","$37,978,162",Michael Bay,https://m.media-amazon.com/images/M/MV5BYjY0OW...,Paramount Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Chuck Hogan (screenplay), Mitchell Zuckoff (book)"
3,tt2304933,"Chloë Grace Moretz, Matthew Zuk, Gabriela Lope...",NaN,J Blakeson,https://m.media-amazon.com/images/M/MV5BMjQwOT...,Sony Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Susannah Grant (screenplay by), Akiva Goldsman..."
4,tt1594972,"Rob Schneider, Heather Graham, Ken Jeong, Bill...","$12,320,716",Trevor Wall,https://m.media-amazon.com/images/M/MV5BNTY4MD...,Lionsgate,"[{'Source': 'Internet Movie Database', 'Value'...","Daniel Altiere, Steven Altiere, Malcolm T. Gol..."

In [ ]:
df_2 = df_2.rename(columns={"Movie_id":"imdb_id"})
df_2.columns

In [5]:
joined_df = pd.merge(df_1, df_2, how='inner', on = 'imdb_id')
joined_df.columns

Index(['id', 'imdb_id', 'title', 'release_date', 'spoken_languages', 'genres',
       'runtime', 'production_companies', 'production_countries', 'budget',
       'revenue', 'overview', 'tagline', 'vote_average', 'vote_count',
       'homepage', 'popularity', 'actors', 'boxoffice', 'director',
       'poster_link', 'production_company', 'ratings', 'writer'],
      dtype='object')

In [2]:
# joined_df.to_csv("joined_data_v1.csv")
joined_df = pd.read_csv("joined_data_v1.csv")
joined_df.head()

,id,imdb_id,title,release_date,spoken_languages,genres1,genres2,genres3,genres4,genres5,...,director,poster_link,production_company,vote_average,vote_average_perc,Internet_Movie_Database_rating,Rotten_Tomatoes_rating,Metacritic_rating,rating_average,writer
0,329440,tt3387542,The Forest,1/7/2016,"[{'iso_639_1': 'en', 'name': 'English'}",Horror,Thriller,NaN,NaN,NaN,...,Jason Zada,https://m.media-amazon.com/images/M/MV5BMjAwMz...,Gramercy Pictures,4.8,0.48,0.48,0.10,0.34,0.35,"Nick Antosca, Sarah Cornwell, Ben Ketai"
1,368031,tt3352390,Friend Request,1/7/2016,"[{'iso_639_1': 'en', 'name': 'English'}",Horror,Thriller,NaN,NaN,NaN,...,Simon Verhoeven,https://m.media-amazon.com/images/M/MV5BNGFhZj...,Entertainment Studios Motion Pictures,5.3,0.53,0.53,0.17,0.31,0.39,"Matthew Ballen, Philip Koch, Simon Verhoeven"
2,300671,tt4172430,13 Hours: The Secret Soldiers of Benghazi,1/13/2016,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Action,Drama,History,Thriller,War,...,Michael Bay,https://m.media-amazon.com/images/M/MV5BYjY0OW...,Paramount Pictures,7.0,0.70,0.73,0.51,0.48,0.61,"Chuck Hogan (screenplay), Mitchell Zuckoff (book)"
3,299687,tt2304933,The 5th Wave,1/14/2016,"[{'iso_639_1': 'en', 'name': 'English'}",Adventure,Science Fiction,NaN,NaN,NaN,...,J Blakeson,https://m.media-amazon.com/images/M/MV5BMjQwOT...,Sony Pictures,5.6,0.56,0.52,0.15,0.33,0.39,"Susannah Grant (screenplay by), Akiva Goldsman..."
4,276905,tt1594972,Norm of the North,1/14/2016,"[{'iso_639_1': 'en', 'name': 'English'}",Adventure,Animation,Comedy,Family,NaN,...,Trevor Wall,https://m.media-amazon.com/images/M/MV5BNTY4MD...,Lionsgate,4.1,0.41,0.36,0.09,0.21,0.27,"Daniel Altiere, Steven Altiere, Malcolm T. Gol..."

In [30]:
import json
# genres = joined_df['genres']
# print(genres[0].dtypes)
# joined_df.describe()
# y = json.loads(joined_df['genres'][0])
# print(y)
joined_df['release_date'][0]

'1/7/2016'

# SQLITE

In [3]:
# Create movie_metadata classes
# ----------------------------------
class Movie(Base):
    __tablename__ = 'movie_metadata'
#     id	imdb_id	title	release_date	spoken_languages	
#     genres1	genres2	genres3	genres4	genres5	runtime	production_companies	
#     production_countries	budget	revenue	overview	tagline	vote_count	
#     homepage	popularity	actors	boxoffice	director	poster_link	
#     production_company	vote_average	vote_average_perc	
#     Internet_Movie_Database_rating	Rotten_Tomatoes_rating	
#     Metacritic_rating	rating_average	writer
    
    id = Column(Integer, primary_key=True)
    imdb_id = Column(String(255))
    title = Column(String(255))
    release_date = Column(String(255))
    spoken_languages = Column(String(255))
    genres1 = Column(String(255))
    genres2 = Column(String(255))
    genres3 = Column(String(255))
    genres4 = Column(String(255))
    genres5 = Column(String(255))
    runtime = Column(String(255))
    production_companies = Column(String(255))
    production_countries = Column(String(255))
    budget = Column(String(255))
    revenue = Column(String(255))
    overview = Column(String(255))
    tagline = Column(String(255))
    vote_count = Column(Float)
    homepage = Column(String(255))
    vote_average = Column(Float)
    vote_average_perc = Column(Float)
    Internet_Movie_Database_rating = Column(Float)
    Rotten_Tomatoes_rating = Column(Float)
    Metacritic_rating = Column(Float)
    rating_average = Column(Float)
    
    
    popularity = Column(String(255))
    actors = Column(String(255))
    boxoffice = Column(String(255))
    director = Column(String(255))
    poster_link = Column(String(255))
    production_company = Column(String(255))
    ratings = Column(String(255))
    writer = Column(String(255))

In [4]:
# Create Database Connection
# ----------------------------------
# Establish Connection
engine = create_engine("sqlite:///movieData.sqlite")
conn = engine.connect()

In [5]:
# Create table within the database
Base.metadata.create_all(conn)

In [6]:
# To push the objects made and query the server we use a Session object
joined_df.to_sql('movie_metadata', con=engine, if_exists='append', index=False)
# engine.execute("SELECT * FROM movie_metadata").fetchall()

OperationalError: (sqlite3.OperationalError) table movie_metadata has no column named genres1 [SQL: 'INSERT INTO movie_metadata (id, imdb_id, title, release_date, spoken_languages, genres1, genres2, genres3, genres4, genres5, runtime, production_companies, production_countries, budget, revenue, overview, tagline, vote_count, homepage, popularity, actors, boxoffice, director, poster_link, production_company, vote_average, vote_average_perc, "Internet_Movie_Database_rating", "Rotten_Tomatoes_rating", "Metacritic_rating", rating_average, writer) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ((329440, 'tt3387542', 'The Forest', '1/7/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Horror', ' Thriller', None, None, None, 95, "[{'name': 'Lava Bear Films', 'id': 32300}, {'name': 'AI-Film', 'id': 51860}, {'name': 'Phantom Four Films', 'id': 69579}]", "[{'iso_3166_1': 'US', 'name': 'United States of America'}]", 10000000, 40055439, 'Set in the Aokigahara Forest, a real-life place in Japan where people go to end their lives. Against this backdrop, a young American woman comes in search of her twin sister, who has mysteriously disappeared.', 'Everyone comes here looking for a way out', 478, 'http://theforestisreal.com/', 7.384688000000001, 'Natalie Dormer, Eoin Macken, Stephanie Vogt, Osamu Tanpopo', 21818536.0, 'Jason Zada', 'https://m.media-amazon.com/images/M/MV5BMjAwMzQzNTc5OV5BMl5BanBnXkFtZTgwNDgyMTU2NzE@._V1_SX300.jpg', 'Gramercy Pictures', 4.8, 0.48, 0.48, 0.1, 0.34, 0.35, 'Nick Antosca, Sarah Cornwell, Ben Ketai'), (368031, 'tt3352390', 'Friend Request', '1/7/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Horror', ' Thriller', None, None, None, 92, "[{'name': 'Wiedemann & Berg Filmproduktion', 'id': 336}, {'name': 'Seven Pictures', 'id': 1107}, {'name': 'Two Oceans Production (TOP)', 'id': 60227}]", "[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'ZA', 'name': 'South Africa'}]", 9900000, 2400000, 'Enjoying college life as a popular student, Laura shares everything with her more  than 800 friends on Facebook. But one day, after accepting a friend request from a  social outcast named Marina, Laura’s life is cursed...', 'Be careful who you click with.', 376, 'http://www.w-b-film.de/', 14.282584, 'Alycia Debnam-Carey, William Moseley, Connor Paolo, Brit Morgan', 3758792.0, 'Simon Verhoeven', 'https://m.media-amazon.com/images/M/MV5BNGFhZjQ5OTEtY2FlMy00OWM5LTlkYjAtZGUyNTE2YmVkYjc0XkEyXkFqcGdeQXVyNjkwMzU3NDI@._V1_SX300.jpg', 'Entertainment Studios Motion Pictures', 5.3, 0.53, 0.53, 0.17, 0.31, 0.39, 'Matthew Ballen, Philip Koch, Simon Verhoeven'), (300671, 'tt4172430', '13 Hours: The Secret Soldiers of Benghazi', '1/13/2016', "[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso_639_1': 'en', 'name': 'English'}", ' Action', ' Drama', 'History', 'Thriller', 'War', 144, "[{'name': 'Paramount Pictures', 'id': 4}, {'name': '3 Arts Entertainment', 'id': 787}, {'name': 'Bay Films', 'id': 6734}, {'name': 'Latina Pictures', 'id': 19108}, {'name': 'Dune Films', 'id': 19477}]", "[{'iso_3166_1': 'MT', 'name': 'Malta'}, {'iso_3166_1': 'MA', 'name': 'Morocco'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]", 50000000, 69411370, 'An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.', 'When everything went wrong, six men had the courage to do what was right.', 963, 'http://www.thirteenhoursmovie.com/', 18.022579, 'John Krasinski, James Badge Dale, Pablo Schreiber, David Denman', 37978162.0, 'Michael Bay', 'https://m.media-amazon.com/images/M/MV5BYjY0OWVjMGQtNTIzZi00OGU5LWI4N2EtMGU0YzQ4OWM4ZmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Paramount Pictures', 7.0, 0.7, 0.73, 0.51, 0.48, 0.61, 'Chuck Hogan (screenplay), Mitchell Zuckoff (book)'), (299687, 'tt2304933', 'The 5th Wave', '1/14/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Adventure', ' Science Fiction', None, None, None, 112, "[{'name': 'Columbia Pictures', 'id': 5}, {'name': 'GK Films', 'id': 3281}, {'name': 'Material Pictures', 'id': 12139}, {'name': 'LStar Capital', 'id': 34034}", "[{'iso_3166_1': 'US', 'name': 'United States of America'}]", 38000000, 109906372, '16-year-old Cassie Sullivan tries to survive in a world devastated by the waves of an alien invasion that has already decimated the population and knocked mankind back to the Stone Age.', 'Protect Your Own', 1993, 'https://www.facebook.com/5thWaveMovie/', 10.788263, 'Chloë Grace Moretz, Matthew Zuk, Gabriela Lopez, Bailey Anne Borders', None, 'J Blakeson', 'https://m.media-amazon.com/images/M/MV5BMjQwOTc0Mzg3Nl5BMl5BanBnXkFtZTgwOTg3NjI2NzE@._V1_SX300.jpg', 'Sony Pictures', 5.6, 0.56, 0.52, 0.15, 0.33, 0.39, 'Susannah Grant (screenplay by), Akiva Goldsman (screenplay by), Jeff Pinkner (screenplay by), Rick Yancey (based on the novel by)'), (276905, 'tt1594972', 'Norm of the North', '1/14/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Adventure', ' Animation', 'Comedy', 'Family', None, 86, "[{'name': 'Lionsgate', 'id': 1632}, {'name': 'Splash Entertainment', 'id': 67327}, {'name': 'Telegael', 'id': 72280}, {'name': 'Assemblage Entertainment', 'id': 72281}", "[{'iso_3166_1': 'US', 'name': 'United States of America'}, {'iso_3166_1': 'IN', 'name': 'India'}", 18000000, 17062499, 'The stereoscopic 3D animated family film "Norm" tells the story of the titular polar bear and his three Arctic lemming buddies, who are forced out in ... (99 characters truncated) ... s life anew as a performing corporate mascot, only to discover that his new employers are directly responsible for the destruction of his polar home.', 'Bear to be different', 124, 'http://www.normofthenorth.movie', 7.008103, 'Rob Schneider, Heather Graham, Ken Jeong, Bill Nighy', 12320716.0, 'Trevor Wall', 'https://m.media-amazon.com/images/M/MV5BNTY4MDk4Mjc4NV5BMl5BanBnXkFtZTgwNzg4OTk0NzE@._V1_SX300.jpg', 'Lionsgate', 4.1, 0.41, 0.36, 0.09, 0.21, 0.27, 'Daniel Altiere, Steven Altiere, Malcolm T. Goldman'), (323675, 'tt2869728', 'Ride Along 2', '1/14/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Action', ' Comedy', None, None, None, 102, "[{'name': 'Universal Pictures', 'id': 33}, {'name': 'Cube Vision', 'id': 2780}, {'name': 'Will Packer Productions', 'id': 49968}, {'name': 'Reel Chefs Catering', 'id': 83397}", "[{'iso_3166_1': 'US', 'name': 'United States of America'}", 40000000, 124827316, "As his wedding day approaches, Ben heads to Miami with his soon-to-be brother-in-law James to bring down a drug dealer who's supplying the dealers of Atlanta with product.", 'The brothers-in-law are back', 567, 'http://www.ridealong.com/', 9.420931, 'Ice Cube, Kevin Hart, Tika Sumpter, Benjamin Bratt', None, 'Tim Story', 'https://m.media-amazon.com/images/M/MV5BMTU4ODAzMzcxOV5BMl5BanBnXkFtZTgwODkxMDI1NjE@._V1_SX300.jpg', 'Universal Pictures', 6.1, 0.61, 0.59, 0.13, 0.32, 0.41, 'Phil Hay, Matt Manfredi, Greg Coolidge (characters)'), (259694, 'tt1292566', 'How to Be Single', '1/21/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Comedy', ' Romance', None, None, None, 110, "[{'name': 'New Line Cinema', 'id': 12}, {'name': 'Flower Films', 'id': 2214}, {'name': 'Metro-Goldwyn-Mayer Pictures', 'id': 6127}", "[{'iso_3166_1': 'US', 'name': 'United States of America'}", 38000000, 112343513, 'New York City is full of lonely hearts seeking the right match, and what Alice, Robin, Lucy, Meg, Tom and David all have in common is the need to learn how to be single in a world filled with ever-evolving definitions of love.', 'Welcome to the party', 1225, 'http://howtobesinglemovie.com/', 8.898988000000001, 'Dakota Johnson, Rebel Wilson, Leslie Mann, Damon Wayans Jr.', None, 'Christian Ditter', 'https://m.media-amazon.com/images/M/MV5BNzI4MDMwMzUwNF5BMl5BanBnXkFtZTgwMDgyNzkyNzE@._V1_SX300.jpg', 'Warner Bros. Pictures', 5.9, 0.59, 0.61, 0.46, 0.51, 0.54, 'Abby Kohn (screenplay), Marc Silverstein (screenplay), Dana Fox (screenplay), Abby Kohn (screen story), Marc Silverstein (screen story), Liz Tuccillo (book)'), (291870, 'tt1860213', 'Dirty Grandpa', '1/21/2016', "[{'iso_639_1': 'en', 'name': 'English'}", ' Comedy', None, None, None, None, 102, '[{\'name\': \'Lionsgate\', \'id\': 1632}, {\'name\': \'Josephson Entertainment\', \'id\': 1894}, {\'name\': \'QED International\', \'id\': 11029}, {\ ... (3 characters truncated) ... me\': "Ninjas Runnin\' Wild Productions", \'id\': 28200}, {\'name\': \'Covert Media\', \'id\': 73666}, {\'name\': \'BillBlock Media\', \'id\': 90185}', "[{'iso_3166_1': 'US', 'name': 'United States of America'}", 11500000, 94073028, "Jason Kelly is one week away from marrying his boss's uber-controlling daughter, putting him on the fast track for a partnership at the law firm. How ... (181 characters truncated) ... iotous frat parties, bar fights, and an epic night of karaoke, Dick is on a quest to live his life to the fullest and bring Jason along for the ride.", "This is Jason. He's a little worried about his grandpa.", 1429, 'http://www.dirtygrandpa.movie/', 16.290585999999998, 'Robert De Niro, Zac Efron, Zoey Deutch, Aubrey Plaza', 34690808.0, 'Dan Mazer', 'https://m.media-amazon.com/images/M/MV5BMzk0NzkyNDk2M15BMl5BanBnXkFtZTgwNDczOTU3NzE@._V1_SX300.jpg', 'Lionsgate Films', 5.7, 0.57, 0.59, 0.11, 0.21, 0.37, 'John Phillips')  ... displaying 10 of 193 total bound parameter sets ...  (378236, 'tt4877122', 'The Emoji Movie', '7/28/2017', "[{'iso_639_1': 'en', 'name': 'English'}", ' Comedy', ' Family', 'Animation', None, None, 86, "[{'name': 'Columbia Pictures', 'id': 5}, {'name': 'Sony Pictures Animation', 'id': 2251}", "[{'iso_3166_1': 'US', 'name': 'United States of America'}", 50000000, 66913939, 'Gene, a multi-expressional emoji, sets out on a journey to become a normal emoji.', 'Not easy being meh', 327, 'http://www.theemoji-movie.com/', 33.694599, 'T.J. Miller, James Corden, Anna Faris, Maya Rudolph', 86053485.0, 'Tony Leondis', 'https://m.media-amazon.com/images/M/MV5BMTkzMzM3OTM2Ml5BMl5BanBnXkFtZTgwMDM0NDU3MjI@._V1_SX300.jpg', 'Sony Pictures Animation', 5.8, 0.58, 0.32, 0.07, 0.12, 0.27, 'Tony Leondis (screenplay by), Eric Siegel (screenplay by), Mike White (screenplay by), Tony Leondis (story by), Eric Siegel (story by), John Hoffman (additional screenplay material)'), (353491, 'tt1648190', 'The Dark Tower', '8/3/2017', "[{'iso_639_1': 'en', 'name': 'English'}", ' Action', ' Western', 'Science Fiction', 'Fantasy', 'Horror', 95, "[{'name': 'Imagine Entertainment', 'id': 23}, {'name': 'Weed Road Pictures', 'id': 433}, {'name': 'Media Rights Capital', 'id': 2531}, {'name': 'Sony Pictures Entertainment', 'id': 5752}", "[{'iso_3166_1': 'ZA', 'name': 'South Africa'}, {'iso_3166_1': 'US', 'name': 'United States of America'}", 60000000, 71000000, 'The last Gunslinger, Roland Deschain, has been locked in an eternal battle with Walter O’Dim, also known as the Man in Black, determined to prevent h ... (65 characters truncated) ... r. With the fate of the worlds at stake, good and evil will collide in the ultimate battle as only Roland can defend the Tower from the Man in Black.', 'There are other worlds than these', 688, 'http://thedarktower-movie.com', 50.903593, 'Matthew McConaughey, Idris Elba, Tom Taylor, Dennis Haysbert', 50644837.0, 'Nikolaj Arcel', 'https://m.media-amazon.com/images/M/MV5BMTU3MjUwMzQ3MF5BMl5BanBnXkFtZTgwMjcwNjkxMjI@._V1_SX300.jpg', 'Sony Pictures', 5.7, 0.57, 0.57, 0.16, 0.34, 0.41, 'Akiva Goldsman (screenplay by), Jeff Pinkner (screenplay by), Anders Thomas Jensen (screenplay by), Nikolaj Arcel (screenplay by), Stephen King (based on "The Dark Tower" novels by)'))] (Background on this error at: http://sqlalche.me/e/e3q8)

In [51]:
# results = engine.execute("SELECT * FROM movie_metadata").fetchall()
results = joined_df
results.head()

,id,imdb_id,title,release_date,spoken_languages,genres,runtime,production_companies,production_countries,budget,...,vote_count,homepage,popularity,actors,boxoffice,director,poster_link,production_company,ratings,writer
0,329440,tt3387542,The Forest,1/7/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",95,"[{'name': 'Lava Bear Films', 'id': 32300}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",10000000,...,478,http://theforestisreal.com/,7.384688,"Natalie Dormer, Eoin Macken, Stephanie Vogt, O...","$21,818,536",Jason Zada,https://m.media-amazon.com/images/M/MV5BMjAwMz...,Gramercy Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Nick Antosca, Sarah Cornwell, Ben Ketai"
1,368031,tt3352390,Friend Request,1/7/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",92,"[{'name': 'Wiedemann & Berg Filmproduktion', '...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",9900000,...,376,http://www.w-b-film.de/,14.282584,"Alycia Debnam-Carey, William Moseley, Connor P...","$3,758,792",Simon Verhoeven,https://m.media-amazon.com/images/M/MV5BNGFhZj...,Entertainment Studios Motion Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Matthew Ballen, Philip Koch, Simon Verhoeven"
2,300671,tt4172430,13 Hours: The Secret Soldiers of Benghazi,1/13/2016,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",144,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'MT', 'name': 'Malta'}, {'iso_...",50000000,...,963,http://www.thirteenhoursmovie.com/,18.022579,"John Krasinski, James Badge Dale, Pablo Schrei...","$37,978,162",Michael Bay,https://m.media-amazon.com/images/M/MV5BYjY0OW...,Paramount Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Chuck Hogan (screenplay), Mitchell Zuckoff (book)"
3,299687,tt2304933,The 5th Wave,1/14/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",112,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...",38000000,...,1993,https://www.facebook.com/5thWaveMovie/,10.788263,"Chloë Grace Moretz, Matthew Zuk, Gabriela Lope...",NaN,J Blakeson,https://m.media-amazon.com/images/M/MV5BMjQwOT...,Sony Pictures,"[{'Source': 'Internet Movie Database', 'Value'...","Susannah Grant (screenplay by), Akiva Goldsman..."
4,276905,tt1594972,Norm of the North,1/14/2016,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",86,"[{'name': 'Lionsgate', 'id': 1632}, {'name': '...","[{'iso_3166_1': 'US', 'name': 'United States o...",18000000,...,124,http://www.normofthenorth.movie,7.008103,"Rob Schneider, Heather Graham, Ken Jeong, Bill...","$12,320,716",Trevor Wall,https://m.media-amazon.com/images/M/MV5BNTY4MD...,Lionsgate,"[{'Source': 'Internet Movie Database', 'Value'...","Daniel Altiere, Steven Altiere, Malcolm T. Gol..."

In [69]:
genres=[]
genres = joined_df.loc[:,'genres'].values
# print(genres)
genre_dict = dict(genres)
print(genres_dict)

ValueError: dictionary update sequence element #0 has length 62; 2 is required

In [53]:
data= []
for result in results:
    print(result)
#     print(len(result[5]))
#     data = result[2]
#     for x in result[5]:
#         print(x)
#     for (int i = 0; i < 4; i++)
#         print(result[5][i])
    i = 0
#     while i < result[5].len:
        
#         for (int i = 0; i < 5; ++i)

id
imdb_id
title
release_date
spoken_languages
genres
runtime
production_companies
production_countries
budget
revenue
overview
tagline
vote_average
vote_count
homepage
popularity
actors
boxoffice
director
poster_link
production_company
ratings
writer

In [68]:
results = engine.execute("SELECT * FROM movie_metadata").fetchall()
print(results[0])

(14564, 'tt0498381', 'Rings', '2/1/2017', "[{'iso_639_1': 'en', 'name': 'English'}]", "[{'id': 27, 'name': 'Horror'}]", '102', "[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'Vertigo Entertainment', 'id': 829}, {'name': 'Macari/Edelstein', 'id': 24902}, {'name': 'Parkes+MacDonald Image Nation', 'id': 49325}, {'name': 'Waddieish Claretrap', 'id': 85425}]", "[{'iso_3166_1': 'US', 'name': 'United States of America'}]", '25000000', '83080890', 'Julia becomes worried about her boyfriend, Holt when he explores the dark urban legend of a mysterious videotape said to kill the watcher seven days  ... (26 characters truncated) ... ces herself to save her boyfriend and in doing so makes a horrifying discovery: there is a "movie within the movie" that no one has ever seen before.', 'Evil is reborn.', '4.8', '1075', 'http://www.ringsmovie.com/', '24.535733', "Matilda Anna Ingrid Lutz, Alex Roe, Johnny Galecki, Vincent D'Onofrio", '$27,766,716 ', 'F. Javier Gutiérrez', 'https://m.media-amazon.com/images/M/MV5BNjU1NDAxNTg0MF5BMl5BanBnXkFtZTgwNzUxMjEwMTI@._V1_SX300.jpg', 'Paramount Pictures', "[{'Source': 'Internet Movie Database', 'Value': '4.5/10'}, {'Source': 'Rotten Tomatoes', 'Value': '7%'}, {'Source': 'Metacritic', 'Value': '25/100'}]", 'David Loucka (screenplay by), Jacob Estes (screenplay by), Akiva Goldsman (screenplay by), David Loucka (story by), Jacob Estes (story by), Kôji Suzuki (based on the novel "The Ring" by)')